Running test_1_add_new_user_route
**********************************
..
----------------------------------------------------------------------
Ran 2 tests in 3.343s

OK
**********************************
Running test_2_add_existent_user
**********************************
..
----------------------------------------------------------------------
Ran 2 tests in 0.983s

OK
**********************************
Running test_3_get_users_route
**********************************
.......
----------------------------------------------------------------------
Ran 7 tests in 3.097s

OK
**********************************
Running test_4_activateUser_account
**********************************
.
----------------------------------------------------------------------
Ran 1 test in 1.137s

OK
**********************************
Running test_5_login.
**********************************
../home/dementedearplug/Projects/Capstone/MJOLNIR/OdinAPI/.venv/lib/python3.7/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
  DeprecationWarning
/home/dementedearplug/Projects/Capstone/MJOLNIR/OdinAPI/.venv/lib/python3.7/site-packages/jwt/api_jws.py:145: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
  DeprecationWarning
..
----------------------------------------------------------------------
Ran 4 tests in 4.660s

OK
**********************************
Running test_6_lockout
**********************************
.
----------------------------------------------------------------------
Ran 1 test in 6.116s

OK
**********************************
Running test_7_reset_invalid_password
**********************************
........
----------------------------------------------------------------------
Ran 8 tests in 1.852s

OK
**********************************
Running test_8_reset_password_route
**********************************
..
----------------------------------------------------------------------
Ran 2 tests in 1.600s

OK
**********************************
Running test_9_toggle_active_state_route
**********************************
..
----------------------------------------------------------------------
Ran 2 tests in 1.152s

OK
**********************************
Running test_10_add_get_user_permissions
**********************************
..
----------------------------------------------------------------------
Ran 2 tests in 0.970s

OK
**********************************
Running test_11_user_set_permissions
**********************************
...F
======================================================================
FAIL: test_set_user_permissions_invalid_format (tests.test_11_user_set_permissions.TestUserRoutes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dementedearplug/Projects/Capstone/MJOLNIR/OdinAPI/tests/test_11_user_set_permissions.py", line 166, in test_set_user_permissions_invalid_format
    self.assertEqual(response.json['Error'], 'Bad Request')
AssertionError: 'Bad Request.' != 'Bad Request'
- Bad Request.
?            -
+ Bad Request


----------------------------------------------------------------------
Ran 4 tests in 1.978s

FAILED (failures=1)
**********************************
Running test_12_remove_user_route
**********************************
..
----------------------------------------------------------------------
Ran 2 tests in 1.193s

OK
**********************************
Running test_13_actions_on_removed_user
**********************************
.......
----------------------------------------------------------------------
Ran 7 tests in 4.842s

OK
